"""
AI Injector module for Skilly.
Autonomously injects project capability and knowledge graph context into
leading AI coding assistants:
- Claude / Claude Code (CLAUDE.md)
- GitHub Copilot (.github/copilot-instructions.md)
- Cursor (.cursorrules & .cursor/rules/skilly.mdc)
- Google Antigravity (AGENTS.md, GEMINI.md, & .agents/rules/skilly.md)
- OpenAI Codex / ChatGPT (CODEX.md)
- Windsurf (.windsurfrules)
- Cline / Roo Code (.clinerules)

Non-destructive and idempotent via standard marker comments:
<!-- SKILLY_INJECTION_START -->
...
<!-- SKILLY_INJECTION_END -->
"""

import os
import re
from pathlib import Path
from typing import Dict, List, Optional
from skilly_core.models import ProjectAnalysisResult

START_MARKER = "<!-- SKILLY_INJECTION_START -->"
END_MARKER = "<!-- SKILLY_INJECTION_END -->"


class AIInjector:
    """Manages injection of Skilly capabilities into AI assistant instruction files."""

    def __init__(self, targets: Optional[List[str]] = None):
        if not targets or "all" in targets:
            self.targets = ["claude", "copilot", "cursor", "antigravity", "codex", "windsurf", "cline"]
        else:
            self.targets = [t.lower().strip() for t in targets]

    def build_directive(self, result: ProjectAnalysisResult) -> str:
        """Build the structured AI guidance block."""
        summary = result.summary
        health = getattr(result, "health", None)
        grade_str = f"`{health.grade}` ({health.score}/100 - {health.summary_text})" if health else "`A`"

        lines = [
            START_MARKER,
            "# 🤖 AI Assistant Context & Project Capabilities (Synthesized by Skilly)",
            "> **Notice for AI Coding Agents**: This repository has an autonomous capability catalog and",
            "> knowledge graph generated by [Skilly](https://github.com/arastuthakur/skilly) (Architected by Arastu Thakur).",
            "> Always consult the generated artifacts below before answering architecture queries, writing code, or running commands.",
            "",
            "### 📚 Available Project Capabilities & Ground Truth",
            "- **Executable Commands & API Routes**: See [`skills.md`](skills.md) for full runnable CLI workflows, curl endpoint invocations, domain models, and exported services.",
            "- **Architectural Topology & Hubs**: See [`knowledge_graph.md`](knowledge_graph.md) and [`knowledge_graph.json`](knowledge_graph.json) for PageRank central components and dependency relationships.",
            "- **Visual Graph**: See [`knowledge_graph.html`](knowledge_graph.html) for an interactive 4K force-directed map of all codebase entities.",
            "",
            "### 📊 Codebase Overview",
            f"- **Architecture Health**: {grade_str}",
            f"- **Total Cataloged Skills**: `{len(result.skills)}`",
            f"- **Languages**: {', '.join(f'{k} ({v})' for k, v in summary.languages.items()) or 'Generic'}",
            f"- **Frameworks / Tooling**: {', '.join(summary.frameworks) or 'Standard Library'}",
            f"- **Knowledge Graph Entities**: `{summary.total_nodes} nodes, {summary.total_edges} relations`",
            "",
            "### 🛠️ Execution Guidelines for AI Agents",
            "1. When asked how to build, test, or run this project, use the exact commands documented in `skills.md`.",
            "2. When adding new endpoints or services, adhere to the architectural hubs and design patterns listed in `skills.md`.",
            "3. To maintain architecture health, avoid introducing circular dependencies detected in `knowledge_graph.md`.",
            END_MARKER,
        ]
        return "\n".join(lines)

    def _inject_file(self, file_path: Path, directive: str, frontmatter: Optional[str] = None) -> bool:
        """
        Safely inject or update directive in file_path.
        Preserves existing user content outside the Skilly marker block.
        """
        file_path.parent.mkdir(parents=True, exist_ok=True)
        content = ""
        if file_path.is_file():
            try:
                content = file_path.read_text(encoding="utf-8", errors="replace")
            except Exception:
                content = ""

        # Pattern to find existing block
        pattern = re.compile(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
            re.DOTALL,
        )

        if pattern.search(content):
            new_content = pattern.sub(directive, content)
        else:
            if content.strip():
                new_content = content.rstrip() + "\n\n" + directive + "\n"
            else:
                if frontmatter:
                    new_content = frontmatter.strip() + "\n\n" + directive + "\n"
                else:
                    new_content = directive + "\n"

        file_path.write_text(new_content, encoding="utf-8")
        return True

    def inject_all(self, target_dir: Path, result: ProjectAnalysisResult) -> Dict[str, Path]:
        """
        Inject Skilly context into all enabled AI coding assistants.
        Returns dict of {tool_name: path_to_file}.
        """
        directive = self.build_directive(result)
        injected: Dict[str, Path] = {}

        # 1. Claude / Claude Code (CLAUDE.md)
        if "claude" in self.targets:
            claude_path = target_dir / "CLAUDE.md"
            self._inject_file(claude_path, directive)
            injected["Claude (CLAUDE.md)"] = claude_path

        # 2. GitHub Copilot (.github/copilot-instructions.md)
        if "copilot" in self.targets:
            copilot_path = target_dir / ".github" / "copilot-instructions.md"
            self._inject_file(copilot_path, directive)
            injected["GitHub Copilot (.github/copilot-instructions.md)"] = copilot_path

        # 3. Cursor (.cursorrules & .cursor/rules/skilly.mdc)
        if "cursor" in self.targets:
            cursorrules_path = target_dir / ".cursorrules"
            self._inject_file(cursorrules_path, directive)
            injected["Cursor (.cursorrules)"] = cursorrules_path

            cursor_mdc_path = target_dir / ".cursor" / "rules" / "skilly.mdc"
            mdc_fm = "---\ndescription: Project Skills & Architecture Context (Skilly)\nglobs: *\nalwaysApply: true\n---"
            self._inject_file(cursor_mdc_path, directive, frontmatter=mdc_fm)
            injected["Cursor (.cursor/rules/skilly.mdc)"] = cursor_mdc_path

        # 4. Google Antigravity (AGENTS.md, GEMINI.md, & .agents/rules/skilly.md)
        if "antigravity" in self.targets:
            agents_path = target_dir / "AGENTS.md"
            self._inject_file(agents_path, directive)
            injected["Antigravity (AGENTS.md)"] = agents_path

            gemini_path = target_dir / "GEMINI.md"
            self._inject_file(gemini_path, directive)
            injected["Antigravity (GEMINI.md)"] = gemini_path

            antigravity_rule = target_dir / ".agents" / "rules" / "skilly.md"
            self._inject_file(antigravity_rule, directive)
            injected["Antigravity (.agents/rules/skilly.md)"] = antigravity_rule

        # 5. OpenAI Codex / ChatGPT (CODEX.md)
        if "codex" in self.targets:
            codex_path = target_dir / "CODEX.md"
            self._inject_file(codex_path, directive)
            injected["OpenAI Codex (CODEX.md)"] = codex_path

        # 6. Windsurf (.windsurfrules)
        if "windsurf" in self.targets:
            windsurf_path = target_dir / ".windsurfrules"
            self._inject_file(windsurf_path, directive)
            injected["Windsurf (.windsurfrules)"] = windsurf_path

        # 7. Cline / Roo Code (.clinerules)
        if "cline" in self.targets:
            cline_path = target_dir / ".clinerules"
            self._inject_file(cline_path, directive)
            injected["Cline (.clinerules)"] = cline_path

        return injected
